import type { Job } from "./types";

// Seed listings so Browse Jobs isn't empty on first load. Marked `seed: true`
// so they're never mixed up with a real giver's own posted-jobs management view.
export const sampleJobs: Job[] = [
  {
    id: "seed-1",
    title: "Full-time cook for a family of four",
    categoryId: "cook",
    description: "Looking for an experienced cook for daily North & South Indian meals. Morning and evening shift, 6 days a week.",
    location: "Koramangala, Bengaluru",
    payType: "monthly",
    payAmount: "₹14,000 / month",
    frequency: "recurring",
    urgent: false,
    verifiedOnly: true,
    postedBy: "Anita Rao",
    postedAt: "2026-06-28",
    status: "open",
    seed: true,
  },
  {
    id: "seed-2",
    title: "Driver needed for daily office commute",
    categoryId: "driver",
    description: "Need a reliable driver with a valid license for daily pickup/drop, Mon–Sat. Own two-wheeler for commute a plus.",
    location: "Andheri East, Mumbai",
    payType: "monthly",
    payAmount: "₹16,000 / month",
    frequency: "recurring",
    urgent: false,
    verifiedOnly: true,
    postedBy: "Rakesh Studios",
    postedAt: "2026-06-30",
    status: "open",
    seed: true,
  },
  {
    id: "seed-3",
    title: "Urgent: electrician for wiring fault",
    categoryId: "electrician",
    description: "Short circuit in the kitchen line, need someone today or tomorrow morning. One-time visit.",
    location: "Sector 62, Noida",
    payType: "fixed",
    payAmount: "₹600 (fixed)",
    frequency: "one-time",
    urgent: true,
    verifiedOnly: false,
    postedBy: "Priya Malhotra",
    postedAt: "2026-07-03",
    status: "open",
    seed: true,
  },
  {
    id: "seed-4",
    title: "Daily housekeeping help, 2 hours/day",
    categoryId: "housekeeping",
    description: "Sweeping, mopping, and dishes, 2 hours every morning. Flexible on exact start time.",
    location: "Salt Lake, Kolkata",
    payType: "monthly",
    payAmount: "₹3,500 / month",
    frequency: "recurring",
    urgent: false,
    verifiedOnly: false,
    postedBy: "Debasish Sen",
    postedAt: "2026-06-25",
    status: "open",
    seed: true,
  },
  {
    id: "seed-5",
    title: "Security guard for apartment complex, night shift",
    categoryId: "security",
    description: "Gated community looking for a night-shift guard, 10pm–6am. Prior experience preferred, uniform provided.",
    location: "Kondapur, Hyderabad",
    payType: "monthly",
    payAmount: "₹13,000 / month",
    frequency: "full-time",
    urgent: false,
    verifiedOnly: true,
    postedBy: "Lakeview Residency",
    postedAt: "2026-06-20",
    status: "open",
    seed: true,
  },
  {
    id: "seed-6",
    title: "Plumber for bathroom leak repair",
    categoryId: "plumber",
    description: "Slow leak under the sink, needs inspection and repair. Flexible timing this week.",
    location: "Indiranagar, Bengaluru",
    payType: "fixed",
    payAmount: "₹500 (fixed)",
    frequency: "one-time",
    urgent: false,
    verifiedOnly: false,
    postedBy: "Vikram Shetty",
    postedAt: "2026-07-01",
    status: "open",
    seed: true,
  },
  {
    id: "seed-7",
    title: "Delivery help for small kirana store",
    categoryId: "delivery",
    description: "Local delivery on a bicycle or scooter, evening hours, 4–8pm daily.",
    location: "Lajpat Nagar, Delhi",
    payType: "daily",
    payAmount: "₹450 / day",
    frequency: "recurring",
    urgent: false,
    verifiedOnly: false,
    postedBy: "Om Kirana Store",
    postedAt: "2026-06-29",
    status: "open",
    seed: true,
  },
  {
    id: "seed-8",
    title: "Construction labour for boundary wall",
    categoryId: "construction",
    description: "Small boundary wall construction job, roughly 5 days of work. Tools provided on site.",
    location: "Wagholi, Pune",
    payType: "daily",
    payAmount: "₹600 / day",
    frequency: "one-time",
    urgent: false,
    verifiedOnly: false,
    postedBy: "Sunil Patil",
    postedAt: "2026-06-27",
    status: "open",
    seed: true,
  },
  {
    id: "seed-9",
    title: "Elder care companion, daytime",
    categoryId: "childcare",
    description: "Looking for a caring, patient person to assist an elderly parent during the day — meals, walks, company.",
    location: "Vastrapur, Ahmedabad",
    payType: "monthly",
    payAmount: "₹12,000 / month",
    frequency: "recurring",
    urgent: false,
    verifiedOnly: true,
    postedBy: "Meera Joshi",
    postedAt: "2026-06-22",
    status: "open",
    seed: true,
  },
  {
    id: "seed-10",
    title: "Painter for 2BHK interior repaint",
    categoryId: "painter",
    description: "Full interior repaint of a 2BHK apartment, roughly 4–5 days of work. Materials to be discussed.",
    location: "Kharadi, Pune",
    payType: "fixed",
    payAmount: "₹9,000 (fixed)",
    frequency: "one-time",
    urgent: false,
    verifiedOnly: false,
    postedBy: "Rohan Deshpande",
    postedAt: "2026-06-24",
    status: "open",
    seed: true,
  },
];
